# Generated by Django 4.2.16 on 2025-08-13 12:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_curriculumlevel_internal_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Audio File', help_text='Descriptive name for this audio file', max_length=200)),
                ('audio_file', models.FileField(upload_to='exams/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'm4a'])])),
                ('start_question', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('end_question', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'start_question'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(help_text='Maximum file size: 10MB', upload_to='exams/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('timer_minutes', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_questions', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('default_options_count', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)])),
                ('passing_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pdf_rotation', models.IntegerField(default=0, help_text='PDF rotation angle in degrees (0, 90, 180, 270)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(270)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_exams_created', to='core.teacher')),
                ('curriculum_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routine_exams', to='core.curriculumlevel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('CHECKBOX', 'Select All'), ('SHORT', 'Short Answer'), ('LONG', 'Long Answer'), ('MIXED', 'Mixed')], max_length=10)),
                ('correct_answer', models.TextField(help_text='For MCQ: single letter, For CHECKBOX: comma-separated letters')),
                ('points', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('options_count', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_assigned_question', to='primepath_routinetest.audiofile')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_questions', to='primepath_routinetest.exam')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(default='', help_text='Contact number for admission interview', max_length=20)),
                ('school_name_manual', models.CharField(blank=True, max_length=200)),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('academic_rank', models.CharField(choices=[('TOP_10', 'Top 10% (English class rank)'), ('TOP_20', 'Top 20% (English class rank)'), ('TOP_30', 'Top 30% (English class rank)'), ('TOP_40', 'Top 40% (English class rank)'), ('TOP_50', 'Top 50% (English class rank)'), ('BELOW_50', 'Below 50% (English class rank)')], max_length=20)),
                ('difficulty_adjustments', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('percentage_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_sessions', to='primepath_routinetest.exam')),
                ('final_curriculum_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_final_sessions', to='core.curriculumlevel')),
                ('original_curriculum_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_original_sessions', to='core.curriculumlevel')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_sessions', to='core.school')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_student_answers', to='primepath_routinetest.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_answers', to='primepath_routinetest.studentsession')),
            ],
            options={
                'ordering': ['question__question_number'],
            },
        ),
        migrations.CreateModel(
            name='DifficultyAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment', models.IntegerField()),
                ('adjusted_at', models.DateTimeField(auto_now_add=True)),
                ('from_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_adjustments_from', to='core.curriculumlevel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_adjustments', to='primepath_routinetest.studentsession')),
                ('to_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_adjustments_to', to='core.curriculumlevel')),
            ],
        ),
        migrations.AddField(
            model_name='audiofile',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_audio_files', to='primepath_routinetest.exam'),
        ),
        migrations.AddIndex(
            model_name='studentsession',
            index=models.Index(fields=['started_at'], name='primepath_r_started_bc9444_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsession',
            index=models.Index(fields=['grade', 'academic_rank'], name='primepath_r_grade_d4e692_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsession',
            index=models.Index(fields=['exam', 'completed_at'], name='primepath_r_exam_id_d8d545_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['session', 'question'], name='primepath_r_session_4457cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('session', 'question')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'question_number'], name='primepath_r_exam_id_abce24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('exam', 'question_number')},
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['curriculum_level', 'is_active'], name='primepath_r_curricu_822162_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['created_at'], name='primepath_r_created_6a51c6_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['exam', 'order'], name='primepath_r_exam_id_f24f2a_idx'),
        ),
    ]
