# Generated by Django 4.2.16 on 2025-08-15 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepath_routinetest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='audio_file',
            field=models.FileField(upload_to='routinetest/exams/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'm4a'])]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='pdf_file',
            field=models.FileField(help_text='Maximum file size: 10MB', upload_to='routinetest/exams/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
