# Generated by Django 4.2.16 on 2025-08-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepath_routinetest', '0002_alter_audiofile_audio_file_alter_exam_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('REVIEW', 'Review Test (Monthly)'), ('QUARTERLY', 'Quarterly Exam')], default='REVIEW', help_text='Type of exam: Review (monthly) or Quarterly', max_length=10),
        ),
    ]
