# Generated by Django 4.2.16 on 2025-08-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepath_routinetest', '0003_exam_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('REVIEW', 'Review / Monthly Exam'), ('QUARTERLY', 'Quarterly Exam')], default='REVIEW', help_text='Type of exam: Review (monthly) or Quarterly', max_length=10),
        ),
    ]
