# Generated by Django 4.2.16 on 2025-08-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepath_routinetest', '0004_alter_exam_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], help_text='Academic year for the exam', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='time_period_month',
            field=models.CharField(blank=True, choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], help_text='Month for Review/Monthly exams', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='time_period_quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1 (Jan-Mar)'), ('Q2', 'Q2 (Apr-Jun)'), ('Q3', 'Q3 (Jul-Sep)'), ('Q4', 'Q4 (Oct-Dec)')], help_text='Quarter for Quarterly exams', max_length=2, null=True),
        ),
    ]
