# Generated by Django 4.2.16 on 2025-08-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepath_routinetest', '0005_exam_academic_year_exam_time_period_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='class_codes',
            field=models.JSONField(blank=True, default=list, help_text="List of class codes this exam applies to (e.g., ['CLASS_7A', 'CLASS_8B'])"),
        ),
    ]
