# Generated by Django 4.2.16 on 2025-08-15 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepath_routinetest', '0006_exam_class_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='allow_late_submission',
            field=models.BooleanField(default=False, help_text='Whether to allow late submissions after scheduled end time'),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='Special instructions for students taking this exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='late_submission_penalty',
            field=models.IntegerField(default=0, help_text='Percentage penalty for late submission (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='exam',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Date when the exam will be conducted', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='scheduled_end_time',
            field=models.TimeField(blank=True, help_text='End time for the exam', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='scheduled_start_time',
            field=models.TimeField(blank=True, help_text='Start time for the exam', null=True),
        ),
    ]
