# Generated by Django 4.2.16 on 2025-08-15 05:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_examlevelmapping_unique_exam_per_mapping'),
        ('primepath_routinetest', '0007_exam_allow_late_submission_exam_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRoster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(blank=True, help_text='School student ID or roll number', max_length=50)),
                ('class_code', models.CharField(choices=[('CLASS_7A', 'Class 7A'), ('CLASS_7B', 'Class 7B'), ('CLASS_7C', 'Class 7C'), ('CLASS_8A', 'Class 8A'), ('CLASS_8B', 'Class 8B'), ('CLASS_8C', 'Class 8C'), ('CLASS_9A', 'Class 9A'), ('CLASS_9B', 'Class 9B'), ('CLASS_9C', 'Class 9C'), ('CLASS_10A', 'Class 10A'), ('CLASS_10B', 'Class 10B'), ('CLASS_10C', 'Class 10C')], help_text="Student's class", max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completion_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('EXCUSED', 'Excused')], default='NOT_STARTED', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text="Special notes about this student's assignment")),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_assignments', to='core.teacher')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_roster', to='primepath_routinetest.exam')),
                ('session', models.ForeignKey(blank=True, help_text='Linked session when student takes the exam', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_entry', to='primepath_routinetest.studentsession')),
            ],
            options={
                'ordering': ['class_code', 'student_name'],
                'indexes': [models.Index(fields=['exam', 'completion_status'], name='primepath_r_exam_id_777249_idx'), models.Index(fields=['exam', 'class_code'], name='primepath_r_exam_id_3d1dbb_idx')],
                'unique_together': {('exam', 'student_name', 'student_id')},
            },
        ),
    ]
