# Generated by Django 4.2.16 on 2025-08-15 05:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_examlevelmapping_unique_exam_per_mapping'),
        ('primepath_routinetest', '0008_studentroster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='allow_late_submission',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='late_submission_penalty',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='scheduled_end_time',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='scheduled_start_time',
        ),
        migrations.AlterField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='General instructions for students taking this exam'),
        ),
        migrations.CreateModel(
            name='ClassExamSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_code', models.CharField(help_text='The specific class this schedule applies to', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, help_text='Date when this class will take the exam', null=True)),
                ('scheduled_start_time', models.TimeField(blank=True, help_text='Start time for this class', null=True)),
                ('scheduled_end_time', models.TimeField(blank=True, help_text='End time for this class', null=True)),
                ('location', models.CharField(blank=True, help_text="Room or location for this class's exam", max_length=100)),
                ('additional_instructions', models.TextField(blank=True, help_text='Additional instructions specific to this class')),
                ('allow_late_submission', models.BooleanField(default=False, help_text='Whether this class can submit late')),
                ('late_submission_penalty', models.IntegerField(default=0, help_text='Percentage penalty for late submission (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is active')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_schedules_created', to='core.teacher')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='primepath_routinetest.exam')),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_start_time', 'class_code'],
                'indexes': [models.Index(fields=['exam', 'class_code'], name='primepath_r_exam_id_df9ca4_idx'), models.Index(fields=['scheduled_date'], name='primepath_r_schedul_df4204_idx')],
                'unique_together': {('exam', 'class_code')},
            },
        ),
    ]
