# Generated by Django 4.2.16 on 2025-08-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepath_routinetest', '0009_remove_exam_allow_late_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='timeslot',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning (8:00 - 12:00)'), ('AFTERNOON', 'Afternoon (12:00 - 16:00)'), ('EVENING', 'Evening (16:00 - 20:00)'), ('FULL_DAY', 'Full Day'), ('FLEXIBLE', 'Flexible Timing')], help_text='Timeslot for the exam (used in naming: [RT] - [January] - [Morning] - CORE Phonics Level 1)', max_length=20, null=True),
        ),
    ]
