# Generated by Django 4.2.16 on 2025-08-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primepath_routinetest', '0010_exam_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='timeslot',
        ),
    ]
