# Generated by Django 4.2.16 on 2025-08-16 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_examlevelmapping_unique_exam_per_mapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primepath_routinetest', '0011_remove_exam_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_code', models.CharField(choices=[('CLASS_7A', 'Class 7A'), ('CLASS_7B', 'Class 7B'), ('CLASS_7C', 'Class 7C'), ('CLASS_8A', 'Class 8A'), ('CLASS_8B', 'Class 8B'), ('CLASS_8C', 'Class 8C'), ('CLASS_9A', 'Class 9A'), ('CLASS_9B', 'Class 9B'), ('CLASS_9C', 'Class 9C'), ('CLASS_10A', 'Class 10A'), ('CLASS_10B', 'Class 10B'), ('CLASS_10C', 'Class 10C')], max_length=20)),
                ('request_type', models.CharField(choices=[('PERMANENT', 'Permanent Assignment'), ('TEMPORARY', 'Temporary Coverage'), ('SUBSTITUTE', 'Substitute Teacher'), ('CO_TEACHING', 'Co-Teaching Arrangement')], default='PERMANENT', max_length=20)),
                ('reason_code', models.CharField(choices=[('NEW_ASSIGNMENT', 'New class assignment'), ('SUBSTITUTE', 'Substituting for another teacher'), ('CO_TEACHING', 'Co-teaching arrangement'), ('CURRICULUM_EXPERTISE', 'Have expertise in curriculum'), ('SCHEDULE_OPTIMIZATION', 'Better schedule alignment'), ('TEACHER_ABSENCE', 'Covering for absent teacher'), ('OTHER', 'Other reason')], default='NEW_ASSIGNMENT', max_length=30)),
                ('reason_text', models.TextField(help_text='Detailed explanation for the request')),
                ('duration_start', models.DateField(blank=True, help_text='Start date for temporary access', null=True)),
                ('duration_end', models.DateField(blank=True, help_text='End date for temporary access', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('WITHDRAWN', 'Withdrawn'), ('MORE_INFO', 'More Information Needed')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes/reason for approval or denial')),
                ('requested_access_level', models.CharField(choices=[('FULL', 'Full Access'), ('VIEW', 'View Only'), ('CO_TEACHER', 'Co-Teacher'), ('SUBSTITUTE', 'Substitute')], default='FULL', max_length=20)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='core.teacher')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherClassAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_code', models.CharField(choices=[('CLASS_7A', 'Class 7A'), ('CLASS_7B', 'Class 7B'), ('CLASS_7C', 'Class 7C'), ('CLASS_8A', 'Class 8A'), ('CLASS_8B', 'Class 8B'), ('CLASS_8C', 'Class 8C'), ('CLASS_9A', 'Class 9A'), ('CLASS_9B', 'Class 9B'), ('CLASS_9C', 'Class 9C'), ('CLASS_10A', 'Class 10A'), ('CLASS_10B', 'Class 10B'), ('CLASS_10C', 'Class 10C')], max_length=20)),
                ('access_level', models.CharField(choices=[('FULL', 'Full Access'), ('VIEW', 'View Only'), ('CO_TEACHER', 'Co-Teacher'), ('SUBSTITUTE', 'Substitute')], default='FULL', max_length=20)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateTimeField(blank=True, help_text='Leave blank for permanent assignment', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this assignment')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('from_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_assignment', to='primepath_routinetest.classaccessrequest')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='core.teacher')),
            ],
            options={
                'ordering': ['class_code', 'teacher__name'],
            },
        ),
        migrations.CreateModel(
            name='AccessAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('REQUEST_CREATED', 'Access Request Created'), ('REQUEST_APPROVED', 'Request Approved'), ('REQUEST_DENIED', 'Request Denied'), ('REQUEST_WITHDRAWN', 'Request Withdrawn'), ('ASSIGNMENT_CREATED', 'Direct Assignment Created'), ('ASSIGNMENT_MODIFIED', 'Assignment Modified'), ('ASSIGNMENT_REVOKED', 'Assignment Revoked'), ('ASSIGNMENT_EXPIRED', 'Assignment Expired'), ('BULK_APPROVAL', 'Bulk Approval'), ('BULK_DENIAL', 'Bulk Denial')], max_length=30)),
                ('class_code', models.CharField(max_length=20)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('related_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='primepath_routinetest.teacherclassassignment')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='primepath_routinetest.classaccessrequest')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_audit_logs', to='core.teacher')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='teacherclassassignment',
            index=models.Index(fields=['teacher', 'is_active'], name='primepath_r_teacher_6a2ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherclassassignment',
            index=models.Index(fields=['class_code', 'is_active'], name='primepath_r_class_c_dcbab1_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherclassassignment',
            index=models.Index(fields=['expires_on'], name='primepath_r_expires_f87518_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherclassassignment',
            unique_together={('teacher', 'class_code', 'is_active')},
        ),
        migrations.AddIndex(
            model_name='classaccessrequest',
            index=models.Index(fields=['teacher', 'status'], name='primepath_r_teacher_fcbd9c_idx'),
        ),
        migrations.AddIndex(
            model_name='classaccessrequest',
            index=models.Index(fields=['status', 'requested_at'], name='primepath_r_status_304d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='classaccessrequest',
            index=models.Index(fields=['class_code', 'status'], name='primepath_r_class_c_9c6139_idx'),
        ),
        migrations.AddIndex(
            model_name='accessauditlog',
            index=models.Index(fields=['teacher', 'timestamp'], name='primepath_r_teacher_08ae04_idx'),
        ),
        migrations.AddIndex(
            model_name='accessauditlog',
            index=models.Index(fields=['class_code', 'timestamp'], name='primepath_r_class_c_3ce9ca_idx'),
        ),
        migrations.AddIndex(
            model_name='accessauditlog',
            index=models.Index(fields=['action', 'timestamp'], name='primepath_r_action_a853fb_idx'),
        ),
    ]
