# Generated by Django 4.2.16 on 2025-08-16 09:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_examlevelmapping_unique_exam_per_mapping'),
        ('primepath_routinetest', '0012_classaccessrequest_teacherclassassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScheduleMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_code', models.CharField(help_text='The class this schedule applies to', max_length=20)),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2025)', max_length=4)),
                ('time_period_type', models.CharField(choices=[('MONTHLY', 'Monthly/Review'), ('QUARTERLY', 'Quarterly')], max_length=10)),
                ('time_period_value', models.CharField(help_text='Month code (JAN-DEC) or Quarter code (Q1-Q4)', max_length=3)),
                ('scheduled_date', models.DateField(blank=True, help_text='Primary scheduled date for exams in this cell', null=True)),
                ('scheduled_start_time', models.TimeField(blank=True, help_text='Default start time for exams', null=True)),
                ('scheduled_end_time', models.TimeField(blank=True, help_text='Default end time for exams', null=True)),
                ('status', models.CharField(choices=[('EMPTY', 'No Exams'), ('SCHEDULED', 'Exams Scheduled'), ('IN_PROGRESS', 'Currently Running'), ('COMPLETED', 'Completed'), ('DRAFT', 'Draft/Planning')], default='EMPTY', max_length=20)),
                ('color_code', models.CharField(default='#FFFFFF', help_text='Hex color code for visual display', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier for status display', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_with_classes', models.JSONField(blank=True, default=list, help_text='List of other class codes this schedule is shared with')),
                ('is_template', models.BooleanField(default=False, help_text='If true, this can be used as a template for other classes')),
                ('notes', models.TextField(blank=True, help_text='Administrative notes about this schedule')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for this matrix cell')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrix_schedules_created', to='core.teacher')),
                ('exams', models.ManyToManyField(blank=True, related_name='matrix_schedules', to='primepath_routinetest.exam')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrix_schedules_modified', to='core.teacher')),
            ],
            options={
                'ordering': ['class_code', 'academic_year', 'time_period_type', 'time_period_value'],
                'indexes': [models.Index(fields=['class_code', 'academic_year'], name='primepath_r_class_c_244d29_idx'), models.Index(fields=['time_period_type', 'time_period_value'], name='primepath_r_time_pe_cfafc0_idx'), models.Index(fields=['status'], name='primepath_r_status_5dce69_idx'), models.Index(fields=['created_by'], name='primepath_r_created_5890b0_idx')],
                'unique_together': {('class_code', 'academic_year', 'time_period_type', 'time_period_value')},
            },
        ),
    ]
