# Generated by Django 4.2.16 on 2025-08-17 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_examlevelmapping_unique_exam_per_mapping'),
        ('primepath_routinetest', '0013_examschedulematrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCurriculumMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_code', models.CharField(db_index=True, help_text='Class code (e.g., 8A, 9B, 10C)', max_length=10)),
                ('academic_year', models.CharField(db_index=True, help_text='Academic year (e.g., 2025)', max_length=4)),
                ('priority', models.IntegerField(default=1, help_text='Priority order when class has multiple curricula (1 = primary)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mapping is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this mapping')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_mappings_created', to=settings.AUTH_USER_MODEL)),
                ('curriculum_level', models.ForeignKey(help_text='The curriculum level assigned to this class', on_delete=django.db.models.deletion.CASCADE, related_name='class_mappings', to='core.curriculumlevel')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_mappings_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Curriculum Mapping',
                'verbose_name_plural': 'Class Curriculum Mappings',
                'ordering': ['class_code', 'priority', '-created_at'],
                'indexes': [models.Index(fields=['class_code', 'academic_year', 'is_active'], name='primepath_r_class_c_b82d56_idx'), models.Index(fields=['curriculum_level', 'academic_year'], name='primepath_r_curricu_22d342_idx')],
                'unique_together': {('class_code', 'curriculum_level', 'academic_year')},
            },
        ),
    ]
