# Generated by Django 4.2.16 on 2025-08-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_examlevelmapping_unique_exam_per_mapping'),
        ('primepath_routinetest', '0015_class_alter_classaccessrequest_class_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='assigned_teachers',
            field=models.ManyToManyField(blank=True, help_text='Teachers assigned to this class', related_name='routinetest_classes', to='core.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'grade_level', 'section', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['is_active', 'academic_year'], name='routinetest_is_acti_18868f_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['grade_level', 'section'], name='routinetest_grade_l_000437_idx'),
        ),
    ]
