# Generated by Django 4.2.16 on 2025-08-18 09:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_rename_core_studen_current_3e8b47_idx_core_studen_current_3aa275_idx_and_more'),
        ('primepath_routinetest', '0017_recreate_studentenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deadline', models.DateTimeField()),
                ('allow_multiple_attempts', models.BooleanField(default=True)),
                ('is_bulk_assignment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'routinetest_exam_assignment',
                'ordering': ['-deadline'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('answers', models.JSONField(default=dict)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('auto_saved_data', models.JSONField(blank=True, default=dict)),
                ('violation_flags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'routinetest_exam_attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutineExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('monthly_review', 'Monthly Review'), ('quarterly', 'Quarterly Exam')], max_length=20)),
                ('curriculum_level', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=10)),
                ('quarter', models.CharField(choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], max_length=2)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='routine_exams/')),
                ('answer_key', models.JSONField(blank=True, default=dict)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'routinetest_exam',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentExamAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('missed', 'Missed')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'routinetest_student_exam_assignment',
            },
        ),
        migrations.RenameIndex(
            model_name='studentenrollment',
            new_name='routinetest_class_a_eaf6b0_idx',
            old_name='routinetest_class_a_4a5d5f_idx',
        ),
        migrations.RenameIndex(
            model_name='studentenrollment',
            new_name='routinetest_student_ac5ae1_idx',
            old_name='routinetest_student_c83b7e_idx',
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='studentexamassignment',
            name='exam_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='primepath_routinetest.examassignment'),
        ),
        migrations.AddField(
            model_name='studentexamassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='core.student'),
        ),
        migrations.AddField(
            model_name='routineexam',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routine_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='primepath_routinetest.studentexamassignment'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='primepath_routinetest.routineexam'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='core.student'),
        ),
        migrations.AddField(
            model_name='examassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_assignments', to='core.teacher'),
        ),
        migrations.AddField(
            model_name='examassignment',
            name='class_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='primepath_routinetest.class'),
        ),
        migrations.AddField(
            model_name='examassignment',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='primepath_routinetest.routineexam'),
        ),
        migrations.AlterUniqueTogether(
            name='studentexamassignment',
            unique_together={('student', 'exam_assignment')},
        ),
        migrations.AddIndex(
            model_name='routineexam',
            index=models.Index(fields=['curriculum_level', 'quarter', 'exam_type'], name='routinetest_curricu_e7d5a3_idx'),
        ),
        migrations.AddIndex(
            model_name='routineexam',
            index=models.Index(fields=['academic_year', 'quarter'], name='routinetest_academi_981a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='routineexam',
            index=models.Index(fields=['is_active'], name='routinetest_is_acti_fba235_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routineexam',
            unique_together={('name', 'academic_year', 'quarter')},
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', 'exam', 'attempt_number'], name='routinetest_student_8d40a4_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['is_submitted', 'submitted_at'], name='routinetest_is_subm_b4245a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together={('student', 'exam', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='examassignment',
            unique_together={('exam', 'class_assigned', 'deadline')},
        ),
    ]
