# Generated by Django 4.2.16 on 2025-08-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepath_routinetest', '0018_examassignment_examattempt_routineexam_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='routineexam',
            name='routinetest_curricu_e7d5a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='routineexam',
            name='routinetest_academi_981a5a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='routineexam',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='routineexam',
            name='time_period_month',
            field=models.CharField(blank=True, choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='routineexam',
            name='time_period_quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='routineexam',
            name='exam_type',
            field=models.CharField(choices=[('REVIEW', 'Monthly Review'), ('QUARTERLY', 'Quarterly Exam')], max_length=20),
        ),
        migrations.AlterField(
            model_name='routineexam',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='routineexam',
            unique_together={('name', 'academic_year', 'time_period_quarter', 'time_period_month')},
        ),
        migrations.AddIndex(
            model_name='routineexam',
            index=models.Index(fields=['curriculum_level', 'time_period_quarter', 'exam_type'], name='routinetest_curricu_5bcc61_idx'),
        ),
        migrations.AddIndex(
            model_name='routineexam',
            index=models.Index(fields=['curriculum_level', 'time_period_month', 'exam_type'], name='routinetest_curricu_194177_idx'),
        ),
        migrations.AddIndex(
            model_name='routineexam',
            index=models.Index(fields=['academic_year', 'time_period_quarter'], name='routinetest_academi_069ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='routineexam',
            index=models.Index(fields=['academic_year', 'time_period_month'], name='routinetest_academi_9816ba_idx'),
        ),
        migrations.AddIndex(
            model_name='routineexam',
            index=models.Index(fields=['exam_type'], name='routinetest_exam_ty_b01b7c_idx'),
        ),
    ]
