# Generated by Django 4.2.16 on 2025-08-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepath_routinetest', '0020_fix_examschedulematrix_routineexam_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classaccessrequest',
            name='requested_access_level',
            field=models.CharField(choices=[('FULL', 'Full Access'), ('VIEW', 'View Only')], default='FULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentroster',
            name='class_code',
            field=models.CharField(choices=[], help_text="Student's class", max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherclassassignment',
            name='access_level',
            field=models.CharField(choices=[('FULL', 'Full Access'), ('VIEW', 'View Only')], default='FULL', max_length=20),
        ),
    ]
