# Generated by Django 4.2.16 on 2025-08-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepath_routinetest', '0023_migrate_class_codes_to_single'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classaccessrequest',
            name='class_code',
            field=models.CharField(choices=[('PS1', 'PS1 - CORE Phonics Level 1'), ('P2', 'P2 - CORE Phonics Level 3'), ('A2', 'A2 - CORE Sigma Level 1'), ('B2', 'B2 - CORE Sigma Level 2'), ('B3', 'B3 - CORE Sigma Level 3'), ('B4', 'B4 - CORE Elite Level 1'), ('B5', 'B5 - CORE Elite Level 2'), ('S2', 'S2 - CORE Elite Level 3'), ('S3', 'S3 - CORE Sigma Level 1'), ('H1', 'H1 - CORE Sigma Level 3'), ('H2', 'H2 - CORE Sigma Level 3'), ('C2', 'C2 - CORE Elite Level 1'), ('C3', 'C3 - CORE Sigma Level 3'), ('C4', 'C4 - CORE Sigma Level 3'), ('C5', 'C5 - CORE Elite Level 1'), ('H3', 'H3 - CORE Elite Level 2'), ('H4', 'H4 - CORE Elite Level 3'), ('Young-cho2', 'Young-cho2 - EDGE Rise Level 1'), ('Chung-cho4', 'Chung-cho4 - EDGE Rise Level 2'), ('Chung-cho1', 'Chung-cho1 - EDGE Rise Level 3'), ('SejongM', 'SejongM - EDGE Pursuit Level 3'), ('MAS', 'MAS - EDGE Pro Level 1'), ('TaejoC', 'TaejoC - ASCENT Drive Level 1'), ('TaejoD', 'TaejoD - ASCENT Drive Level 2'), ('TaejoE', 'TaejoE - ASCENT Drive Level 3'), ('TaejoG', 'TaejoG - ASCENT Drive Level 3'), ('SungjongM', 'SungjongM - ASCENT Pro Level 1'), ('Sungjong2', 'Sungjong2 - ASCENT Pro Level 2'), ('Sungjong3', 'Sungjong3 - EDGE Spark Level 1'), ('Sungjong4', 'Sungjong4 - EDGE Spark Level 2'), ('Young-choM', 'Young-choM - EDGE Spark Level 3'), ('D2', 'D2 - ASCENT Nova Level 1'), ('D3', 'D3 - ASCENT Nova Level 1'), ('D4', 'D4 - ASCENT Nova Level 2'), ('High1.SatSun.3-5', 'High1.SatSun.3-5 - PINNACLE Vision Level 1'), ('High1.SatSun.5-7', 'High1.SatSun.5-7 - PINNACLE Vision Level 1'), ('High1/2.SatSun.11-1', 'High1/2.SatSun.11-1 - PINNACLE Endeavor Level 2'), ('High1/2.SatSun.1-3', 'High1/2.SatSun.1-3 - PINNACLE Endeavor Level 2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='exam',
            name='class_code',
            field=models.CharField(blank=True, choices=[], db_index=True, help_text='Single class code this exam belongs to (one-to-one relationship)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='class_codes',
            field=models.JSONField(blank=True, default=list, help_text='DEPRECATED: List of class codes (migrate to class_code field)'),
        ),
        migrations.AlterField(
            model_name='teacherclassassignment',
            name='class_code',
            field=models.CharField(choices=[('PS1', 'PS1 - CORE Phonics Level 1'), ('P2', 'P2 - CORE Phonics Level 3'), ('A2', 'A2 - CORE Sigma Level 1'), ('B2', 'B2 - CORE Sigma Level 2'), ('B3', 'B3 - CORE Sigma Level 3'), ('B4', 'B4 - CORE Elite Level 1'), ('B5', 'B5 - CORE Elite Level 2'), ('S2', 'S2 - CORE Elite Level 3'), ('S3', 'S3 - CORE Sigma Level 1'), ('H1', 'H1 - CORE Sigma Level 3'), ('H2', 'H2 - CORE Sigma Level 3'), ('C2', 'C2 - CORE Elite Level 1'), ('C3', 'C3 - CORE Sigma Level 3'), ('C4', 'C4 - CORE Sigma Level 3'), ('C5', 'C5 - CORE Elite Level 1'), ('H3', 'H3 - CORE Elite Level 2'), ('H4', 'H4 - CORE Elite Level 3'), ('Young-cho2', 'Young-cho2 - EDGE Rise Level 1'), ('Chung-cho4', 'Chung-cho4 - EDGE Rise Level 2'), ('Chung-cho1', 'Chung-cho1 - EDGE Rise Level 3'), ('SejongM', 'SejongM - EDGE Pursuit Level 3'), ('MAS', 'MAS - EDGE Pro Level 1'), ('TaejoC', 'TaejoC - ASCENT Drive Level 1'), ('TaejoD', 'TaejoD - ASCENT Drive Level 2'), ('TaejoE', 'TaejoE - ASCENT Drive Level 3'), ('TaejoG', 'TaejoG - ASCENT Drive Level 3'), ('SungjongM', 'SungjongM - ASCENT Pro Level 1'), ('Sungjong2', 'Sungjong2 - ASCENT Pro Level 2'), ('Sungjong3', 'Sungjong3 - EDGE Spark Level 1'), ('Sungjong4', 'Sungjong4 - EDGE Spark Level 2'), ('Young-choM', 'Young-choM - EDGE Spark Level 3'), ('D2', 'D2 - ASCENT Nova Level 1'), ('D3', 'D3 - ASCENT Nova Level 1'), ('D4', 'D4 - ASCENT Nova Level 2'), ('High1.SatSun.3-5', 'High1.SatSun.3-5 - PINNACLE Vision Level 1'), ('High1.SatSun.5-7', 'High1.SatSun.5-7 - PINNACLE Vision Level 1'), ('High1/2.SatSun.11-1', 'High1/2.SatSun.11-1 - PINNACLE Endeavor Level 2'), ('High1/2.SatSun.1-3', 'High1/2.SatSun.1-3 - PINNACLE Endeavor Level 2')], max_length=30),
        ),
    ]
