# Generated by Django 4.2.16 on 2025-08-24 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primepath_routinetest', '0024_alter_classaccessrequest_class_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamLaunchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_code', models.CharField(help_text='Class code this exam is launched for', max_length=10)),
                ('launched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.IntegerField(help_text='Custom duration for this launch (overrides exam default)')),
                ('expires_at', models.DateTimeField(help_text='When this exam launch expires and is no longer accessible')),
                ('selected_student_ids', models.JSONField(blank=True, default=list, help_text='List of student IDs allowed to take this exam. Empty = all students')),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launch_sessions', to='primepath_routinetest.routineexam')),
                ('launched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_launches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'routinetest_exam_launch_session',
                'ordering': ['-launched_at'],
                'indexes': [models.Index(fields=['class_code', 'is_active'], name='routinetest_class_c_4743e1_idx'), models.Index(fields=['expires_at'], name='routinetest_expires_67e0ca_idx')],
            },
        ),
    ]
