# Generated by Django 4.2.16 on 2025-08-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepath_routinetest', '0025_add_exam_launch_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineexam',
            name='duration',
            field=models.IntegerField(default=60, help_text='Exam duration in minutes'),
        ),
        migrations.AddField(
            model_name='routineexam',
            name='instructions',
            field=models.TextField(blank=True, help_text='Exam instructions for students'),
        ),
    ]
