# Generated by Django 4.2.16 on 2025-08-25 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'add_kakao_fields'),
        ('primepath_routinetest', '0026_routineexam_duration_routineexam_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='is_teacher_preview',
            field=models.BooleanField(default=False, help_text='True if this is a teacher previewing the exam, not a real student session'),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='preview_teacher',
            field=models.ForeignKey(blank=True, help_text='The teacher who is previewing this exam', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview_sessions', to='core.teacher'),
        ),
    ]
