# Generated by Phase 2 Model Unification - Step 2.2
# Django 5.0.1 on 2025-08-26 18:50

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepath_routinetest', '0028_add_program_fields_to_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineexam',
            name='answer_key',
            field=models.JSONField(blank=True, default=dict, help_text='Answer key data (from ManagedExam unification)'),
        ),
        migrations.AddField(
            model_name='routineexam',
            name='version',
            field=models.IntegerField(default=1, help_text='Exam version number (from ManagedExam unification)', validators=[MinValueValidator(1)]),
        ),
    ]