# Generated by Django 5.0.1 on 2025-08-01 02:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_curriculumlevel_created_at_and_more'),
        ('placement_test', '0003_alter_exam_passing_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options_count',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='curriculum_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.curriculumlevel'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('CHECKBOX', 'Select All'), ('SHORT', 'Short Answer'), ('LONG', 'Long Answer'), ('MIXED', 'Mixed')], max_length=10),
        ),
    ]
