# Generated by Django 5.0.1 on 2025-08-01 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_test', '0004_question_options_count_alter_exam_curriculum_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='default_options_count',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
