# Generated by Django 5.0.1 on 2025-08-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_test', '0007_add_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='audiofile',
            new_name='placement_t_exam_id_264cb0_idx',
            old_name='placement_t_exam_order_idx',
        ),
        migrations.RenameIndex(
            model_name='exam',
            new_name='placement_t_curricu_dc7207_idx',
            old_name='placement_t_curr_active_idx',
        ),
        migrations.RenameIndex(
            model_name='exam',
            new_name='placement_t_created_dcbb8b_idx',
            old_name='placement_t_created_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='placement_t_exam_id_8c2610_idx',
            old_name='placement_t_exam_qnum_idx',
        ),
        migrations.RenameIndex(
            model_name='studentanswer',
            new_name='placement_t_session_2d0f45_idx',
            old_name='placement_t_sess_quest_idx',
        ),
        migrations.RenameIndex(
            model_name='studentsession',
            new_name='placement_t_started_9fc6a7_idx',
            old_name='placement_t_started_7c5d8f_idx',
        ),
        migrations.RenameIndex(
            model_name='studentsession',
            new_name='placement_t_grade_2df7d8_idx',
            old_name='placement_t_grade_ac_rank_idx',
        ),
        migrations.RenameIndex(
            model_name='studentsession',
            new_name='placement_t_exam_id_6a8b91_idx',
            old_name='placement_t_exam_comp_idx',
        ),
        migrations.AddField(
            model_name='exam',
            name='skip_first_left_half',
            field=models.BooleanField(default=False, help_text='Skip the first left half of page 1 in column view'),
        ),
    ]
