# Generated by Django 5.0.1 on 2025-08-02 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_test', '0008_rename_placement_t_exam_order_idx_placement_t_exam_id_264cb0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_question', to='placement_test.audiofile'),
        ),
    ]
