# Generated by Django 5.0.1 on 2025-08-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_test', '0010_convert_audio_assignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='skip_first_left_half',
        ),
    ]
