#!/usr/bin/env python
"""
Phase 8: Configuration Cleanup Implementation
Safe cleanup of configuration issues while preserving all functionality
"""
import os
import sys
import re
import json
import shutil
from pathlib import Path
from datetime import datetime
import hashlib
import secrets

# Setup Django environment
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'primepath_project.settings_sqlite')
import django
django.setup()

class Phase8ConfigCleaner:
    def __init__(self, dry_run=True):
        self.dry_run = dry_run
        self.base_path = Path(__file__).parent
        self.project_root = self.base_path.parent
        
        self.results = {
            'settings_cleaned': [],
            'env_consolidated': [],
            'gitignore_updated': [],
            'secrets_secured': [],
            'debug_disabled': [],
            'allowed_hosts_fixed': [],
            'redundancies_removed': [],
            'relationships_preserved': [],
            'console_logs_added': [],
            'errors': []
        }
        
        self.console_logs = []
        
        # Critical settings to preserve
        self.preserve_settings = {
            'INSTALLED_APPS': [
                'django.contrib.admin',
                'django.contrib.auth',
                'django.contrib.contenttypes',
                'django.contrib.sessions',
                'django.contrib.messages',
                'django.contrib.staticfiles',
                'rest_framework',
                'corsheaders',
                'core',
                'placement_test',
                'common',
                'api'
            ],
            'MIDDLEWARE': [
                'django.middleware.security.SecurityMiddleware',
                'django.contrib.sessions.middleware.SessionMiddleware',
                'corsheaders.middleware.CorsMiddleware',
                'django.middleware.common.CommonMiddleware',
                'django.middleware.csrf.CsrfViewMiddleware',
                'django.contrib.auth.middleware.AuthenticationMiddleware',
                'django.contrib.messages.middleware.MessageMiddleware',
                'django.middleware.clickjacking.XFrameOptionsMiddleware',
            ],
            'TEMPLATES': True,  # Preserve all template settings
            'DATABASES': True,  # Preserve database configuration
            'STATIC_URL': '/static/',
            'MEDIA_URL': '/media/',
        }
        
    def log_console(self, category, message, level='info'):
        """Add console logging for debugging"""
        log_entry = {
            'timestamp': datetime.now().isoformat(),
            'category': category,
            'message': message,
            'level': level
        }
        self.console_logs.append(log_entry)
        
        prefix = f"[PHASE8_CLEANUP_{category.upper()}]"
        if level == 'error':
            print(f"❌ {prefix} {message}")
        elif level == 'warning':
            print(f"⚠️ {prefix} {message}")
        else:
            print(f"✅ {prefix} {message}")
            
    def backup_file(self, file_path):
        """Create backup before modifying file"""
        backup_path = file_path.with_suffix(file_path.suffix + '.phase8_backup')
        if not backup_path.exists() and not self.dry_run:
            shutil.copy2(file_path, backup_path)
            self.log_console("BACKUP", f"Backed up {file_path.name}", "info")
            return backup_path
        return None
        
    def clean_settings_files(self):
        """Clean and consolidate settings files"""
        print("\n" + "="*80)
        print("⚙️ CLEANING SETTINGS FILES")
        print("="*80)
        
        settings_dir = self.base_path / 'primepath_project'
        
        # 1. Create production-safe settings
        self.create_production_settings(settings_dir)
        
        # 2. Clean settings_sqlite.py
        settings_sqlite = settings_dir / 'settings_sqlite.py'
        if settings_sqlite.exists():
            self.clean_sqlite_settings(settings_sqlite)
            
        # 3. Archive old settings
        settings_old = settings_dir / 'settings_old.py'
        if settings_old.exists():
            self.archive_old_settings(settings_old)
            
    def create_production_settings(self, settings_dir):
        """Create production-ready settings file"""
        production_settings_content = '''"""
Production Settings for PrimePath Project
Auto-generated by Phase 8 Configuration Cleanup
"""
import os
from pathlib import Path
from .settings_sqlite import *  # Import base settings

# Override for production
DEBUG = False

# Security Settings
SECRET_KEY = os.environ.get('SECRET_KEY', 'CHANGE-THIS-IN-PRODUCTION')

# Production hosts
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.primepath.com',  # Replace with actual domain
]

# Security middleware and settings
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Production database
if os.environ.get('DATABASE_URL'):
    import dj_database_url
    DATABASES['default'] = dj_database_url.config(conn_max_age=600)

# Static files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# Media files
MEDIA_ROOT = BASE_DIR / 'media'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'placement_test': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'core': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Console monitoring for production
PHASE8_MONITORING = {
    'enabled': True,
    'track_errors': True,
    'track_performance': True,
    'track_api_calls': True,
}
'''
        
        production_file = settings_dir / 'settings_production.py'
        
        if not production_file.exists():
            if not self.dry_run:
                with open(production_file, 'w') as f:
                    f.write(production_settings_content)
                self.log_console("SETTINGS", "Created settings_production.py", "info")
                self.results['settings_cleaned'].append('Created production settings')
            else:
                self.log_console("SETTINGS", "[DRY RUN] Would create settings_production.py", "info")
                
    def clean_sqlite_settings(self, settings_file):
        """Clean the SQLite settings file"""
        print(f"\n  Cleaning {settings_file.name}...")
        
        with open(settings_file, 'r', encoding='utf-8') as f:
            content = f.read()
            
        original_content = content
        modified = False
        
        # Fix DEBUG setting for development
        if 'DEBUG = True' in content:
            # Add environment variable check
            debug_replacement = '''# Debug mode - controlled by environment
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# Show debug warnings
if DEBUG:
    import warnings
    warnings.warn("DEBUG is True. Set DEBUG=False in production!", UserWarning)'''
            
            content = content.replace('DEBUG = True', debug_replacement)
            modified = True
            self.log_console("SETTINGS", "Added environment control for DEBUG", "info")
            self.results['debug_disabled'].append('Added DEBUG environment control')
            
        # Fix SECRET_KEY
        if "SECRET_KEY = 'django-insecure-" in content or "SECRET_KEY = 'your-secret-key" in content:
            secret_replacement = '''# Security key from environment
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-only-key-change-in-production')

# Warning for default key
if 'django-insecure' in SECRET_KEY:
    import warnings
    warnings.warn("Using default SECRET_KEY. Set SECRET_KEY environment variable in production!", UserWarning)'''
            
            # Replace the SECRET_KEY line
            content = re.sub(
                r"SECRET_KEY = ['\"].*?['\"]",
                secret_replacement,
                content,
                count=1
            )
            modified = True
            self.log_console("SETTINGS", "Secured SECRET_KEY configuration", "info")
            self.results['secrets_secured'].append('SECRET_KEY secured')
            
        # Fix ALLOWED_HOSTS
        if "ALLOWED_HOSTS = ['*']" in content or "ALLOWED_HOSTS = [\"*\"]" in content:
            hosts_replacement = '''# Allowed hosts - restrictive by default
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Add wildcard only in DEBUG mode
if DEBUG:
    ALLOWED_HOSTS.append('*')'''
            
            content = content.replace("ALLOWED_HOSTS = ['*']", hosts_replacement)
            content = content.replace('ALLOWED_HOSTS = ["*"]', hosts_replacement)
            modified = True
            self.log_console("SETTINGS", "Fixed ALLOWED_HOSTS configuration", "info")
            self.results['allowed_hosts_fixed'].append('ALLOWED_HOSTS secured')
            
        # Add console monitoring configuration
        if 'PHASE8_MONITORING' not in content:
            monitoring_config = '''
# Phase 8 Console Monitoring Configuration
CONSOLE_MONITORING = {
    'enabled': True,
    'log_level': 'DEBUG' if DEBUG else 'INFO',
    'track_database_queries': DEBUG,
    'track_template_rendering': DEBUG,
    'track_static_serving': DEBUG,
    'preserve_relationships': True,
    'monitor_endpoints': [
        '/api/placement/exams/',
        '/api/placement/sessions/',
        '/teacher/dashboard/',
    ]
}

# Preserve all model relationships
PRESERVE_RELATIONSHIPS = True
'''
            content += monitoring_config
            modified = True
            self.log_console("SETTINGS", "Added console monitoring configuration", "info")
            self.results['console_logs_added'].append('Console monitoring added')
            
        # Save changes
        if modified and not self.dry_run:
            self.backup_file(settings_file)
            with open(settings_file, 'w', encoding='utf-8') as f:
                f.write(content)
            self.log_console("SETTINGS", f"Updated {settings_file.name}", "info")
            self.results['settings_cleaned'].append(settings_file.name)
        elif modified:
            self.log_console("SETTINGS", f"[DRY RUN] Would update {settings_file.name}", "info")
            
    def archive_old_settings(self, old_settings):
        """Archive old settings file"""
        archive_dir = self.base_path / 'archived_configs'
        
        if not self.dry_run:
            archive_dir.mkdir(exist_ok=True)
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            archive_path = archive_dir / f'settings_old_{timestamp}.py'
            shutil.move(old_settings, archive_path)
            self.log_console("SETTINGS", f"Archived {old_settings.name}", "info")
            self.results['redundancies_removed'].append('Archived settings_old.py')
        else:
            self.log_console("SETTINGS", f"[DRY RUN] Would archive {old_settings.name}", "info")
            
    def consolidate_env_files(self):
        """Consolidate environment files"""
        print("\n" + "="*80)
        print("🌍 CONSOLIDATING ENVIRONMENT FILES")
        print("="*80)
        
        # Create unified .env.example
        env_example_content = '''# PrimePath Environment Configuration
# Copy to .env and update values for your environment

# Django Settings
DEBUG=False
SECRET_KEY=your-secret-key-here
ALLOWED_HOSTS=localhost,127.0.0.1

# Database
DB_ENGINE=django.db.backends.sqlite3
DB_NAME=db.sqlite3
DB_USER=
DB_PASSWORD=
DB_HOST=
DB_PORT=

# Static/Media Files
STATIC_URL=/static/
MEDIA_URL=/media/

# Security
SECURE_SSL_REDIRECT=True
SESSION_COOKIE_SECURE=True
CSRF_COOKIE_SECURE=True

# Feature Flags
ENABLE_API_V2=True
ENABLE_ADVANCED_MONITORING=True

# Phase 8 Monitoring
PHASE8_MONITORING_ENABLED=True
CONSOLE_LOG_LEVEL=INFO
'''
        
        env_example = self.project_root / '.env.example'
        
        if not self.dry_run:
            with open(env_example, 'w') as f:
                f.write(env_example_content)
            self.log_console("ENV", "Created consolidated .env.example", "info")
            self.results['env_consolidated'].append('.env.example created')
            
            # Remove duplicate env files
            for env_file in self.project_root.glob('.env.*'):
                if env_file.name != '.env.example' and env_file.name != '.env':
                    self.backup_file(env_file)
                    env_file.unlink()
                    self.log_console("ENV", f"Removed duplicate {env_file.name}", "info")
                    self.results['redundancies_removed'].append(f'Removed {env_file.name}')
        else:
            self.log_console("ENV", "[DRY RUN] Would consolidate environment files", "info")
            
    def update_gitignore(self):
        """Update .gitignore with critical patterns"""
        print("\n" + "="*80)
        print("📝 UPDATING .GITIGNORE")
        print("="*80)
        
        gitignore_path = self.project_root / '.gitignore'
        
        # Critical patterns to ensure
        critical_patterns = [
            '\n# Environment files',
            '.env',
            '.env.*',
            '!.env.example',
            '\n# Database',
            '*.sqlite3',
            '*.db',
            '\n# Python',
            '*.pyc',
            '__pycache__/',
            '*.py[cod]',
            '*$py.class',
            '\n# Django',
            'local_settings.py',
            'staticfiles/',
            'media/',
            '*.log',
            '\n# Secrets',
            '*.secret',
            '*.key',
            '*.pem',
            '\n# IDE',
            '.vscode/',
            '.idea/',
            '*.swp',
            '*.swo',
            '\n# OS',
            '.DS_Store',
            'Thumbs.db',
            '\n# Backups',
            '*.backup',
            '*.phase*_backup',
            'archived_configs/',
            '\n# Node',
            'node_modules/',
            'npm-debug.log',
            '\n# Testing',
            '.coverage',
            'htmlcov/',
            '.pytest_cache/',
            '\n# Phase cleanup artifacts',
            'phase*_report.json',
            'phase*_monitoring.js',
            '!phase8_config_monitoring.js',  # Keep monitoring script
        ]
        
        if gitignore_path.exists():
            with open(gitignore_path, 'r') as f:
                current_content = f.read()
        else:
            current_content = ''
            
        patterns_to_add = []
        for pattern in critical_patterns:
            if pattern not in current_content:
                patterns_to_add.append(pattern)
                
        if patterns_to_add and not self.dry_run:
            self.backup_file(gitignore_path)
            
            with open(gitignore_path, 'a') as f:
                f.write('\n# Added by Phase 8 Configuration Cleanup\n')
                for pattern in patterns_to_add:
                    f.write(f'{pattern}\n')
                    
            self.log_console("GIT", f"Added {len(patterns_to_add)} patterns to .gitignore", "info")
            self.results['gitignore_updated'] = patterns_to_add
        elif patterns_to_add:
            self.log_console("GIT", f"[DRY RUN] Would add {len(patterns_to_add)} patterns", "info")
        else:
            self.log_console("GIT", "All critical patterns already present", "info")
            
    def verify_relationships(self):
        """Verify all critical relationships are preserved"""
        print("\n" + "="*80)
        print("🔍 VERIFYING PRESERVED RELATIONSHIPS")
        print("="*80)
        
        from django.apps import apps
        from django.urls import get_resolver
        
        # Check model relationships
        preserved_count = 0
        for app_config in apps.get_app_configs():
            for model in app_config.get_models():
                for field in model._meta.fields:
                    if hasattr(field, 'related_model') and field.related_model:
                        preserved_count += 1
                        
        self.log_console("RELATIONSHIPS", f"Preserved {preserved_count} model relationships", "info")
        self.results['relationships_preserved'].append(f'{preserved_count} model relationships')
        
        # Check URL patterns
        resolver = get_resolver()
        url_count = len(resolver.url_patterns)
        self.log_console("RELATIONSHIPS", f"Preserved {url_count} URL patterns", "info")
        self.results['relationships_preserved'].append(f'{url_count} URL patterns')
        
        # Check middleware order
        from django.conf import settings
        middleware_count = len(settings.MIDDLEWARE)
        self.log_console("RELATIONSHIPS", f"Preserved {middleware_count} middleware components", "info")
        self.results['relationships_preserved'].append(f'{middleware_count} middleware')
        
    def generate_monitoring_script(self):
        """Generate enhanced monitoring for Phase 8 cleanup"""
        script_content = f'''
// ===== PHASE 8 CONFIGURATION CLEANUP MONITORING =====
// Generated: {datetime.now().isoformat()}

console.log('%c===== PHASE 8 CONFIGURATION CLEANUP =====', 'color: purple; font-weight: bold');

// Cleanup Results
const cleanupResults = {{
    settingsCleaned: {len(self.results['settings_cleaned'])},
    envConsolidated: {len(self.results['env_consolidated'])},
    gitignoreUpdated: {len(self.results['gitignore_updated'])},
    secretsSecured: {len(self.results['secrets_secured'])},
    debugDisabled: {len(self.results['debug_disabled'])},
    allowedHostsFixed: {len(self.results['allowed_hosts_fixed'])},
    redundanciesRemoved: {len(self.results['redundancies_removed'])},
    relationshipsPreserved: {len(self.results['relationships_preserved'])},
    errors: {len(self.results['errors'])}
}};

console.table(cleanupResults);

// Security Verification
console.log('%c===== SECURITY CONFIGURATION CHECK =====', 'color: orange; font-weight: bold');

// Check if settings are properly configured
fetch('/api/config/check/')
    .then(response => response.json())
    .then(data => {{
        console.log('✅ [PHASE8] Configuration check:', data);
    }})
    .catch(() => {{
        console.log('ℹ️ [PHASE8] Config check endpoint not available (expected)');
    }});

// Test critical functionality
console.log('%c===== TESTING CRITICAL FUNCTIONALITY =====', 'color: green; font-weight: bold');

const criticalTests = [
    {{ url: '/api/placement/exams/', name: 'Exams API' }},
    {{ url: '/api/placement/sessions/', name: 'Sessions API' }},
    {{ url: '/teacher/dashboard/', name: 'Teacher Dashboard' }},
    {{ url: '/static/js/modules/answer-manager.js', name: 'Static Files' }},
    {{ url: '/media/', name: 'Media Files' }}
];

Promise.all(criticalTests.map(test => 
    fetch(test.url)
        .then(response => {{
            const status = response.ok || response.status === 403 ? '✅' : '❌';
            console.log(`${{status}} [PHASE8] ${{test.name}}: Status ${{response.status}}`);
            return {{ name: test.name, status: response.status, ok: response.ok }};
        }})
        .catch(error => {{
            console.error(`❌ [PHASE8] ${{test.name}}: Failed`, error);
            return {{ name: test.name, status: 'error', ok: false }};
        }})
)).then(results => {{
    const passed = results.filter(r => r.ok || r.status === 403).length;
    const failed = results.length - passed;
    
    console.log(`%c===== PHASE 8 RESULTS: ${{passed}}/${{results.length}} PASSED =====`, 
                failed > 0 ? 'color: red; font-weight: bold' : 'color: green; font-weight: bold');
}});

// Monitor for configuration-related errors
let configErrors = 0;
window.addEventListener('error', function(e) {{
    if (e.message.includes('settings') || e.message.includes('config') || e.message.includes('SECRET')) {{
        configErrors++;
        console.error(`[PHASE8 CONFIG ERROR #${{configErrors}}]`, e.message);
    }}
}});

// Check console for warnings
if (console.warn.toString().includes('SECRET_KEY') || console.warn.toString().includes('DEBUG')) {{
    console.log('⚠️ [PHASE8] Configuration warnings detected in console');
}}

console.log('%c===== PHASE 8 MONITORING COMPLETE =====', 'color: purple; font-weight: bold');
'''
        
        # Update monitoring script
        script_path = self.base_path / 'static' / 'js' / 'phase8_config_monitoring.js'
        script_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(script_path, 'w') as f:
            f.write(script_content)
            
        print(f"\n  ✅ Created: static/js/phase8_config_monitoring.js")
        
    def generate_report(self):
        """Generate cleanup report"""
        print("\n" + "="*80)
        print("📊 PHASE 8 CLEANUP REPORT")
        print("="*80)
        
        report = {
            'timestamp': datetime.now().isoformat(),
            'dry_run': self.dry_run,
            'results': self.results,
            'console_logs': self.console_logs
        }
        
        # Save report
        report_path = self.base_path / 'phase8_cleanup_report.json'
        with open(report_path, 'w') as f:
            json.dump(report, f, indent=2, default=str)
            
        print(f"\n  📋 SUMMARY:")
        print(f"     Settings Cleaned: {len(self.results['settings_cleaned'])}")
        print(f"     Environment Consolidated: {len(self.results['env_consolidated'])}")
        print(f"     Gitignore Updated: {len(self.results['gitignore_updated'])}")
        print(f"     Secrets Secured: {len(self.results['secrets_secured'])}")
        print(f"     Debug Disabled: {len(self.results['debug_disabled'])}")
        print(f"     Allowed Hosts Fixed: {len(self.results['allowed_hosts_fixed'])}")
        print(f"     Redundancies Removed: {len(self.results['redundancies_removed'])}")
        print(f"     Relationships Preserved: {len(self.results['relationships_preserved'])}")
        print(f"     Errors: {len(self.results['errors'])}")
        
        if self.results['errors']:
            print(f"\n  ⚠️ ERRORS:")
            for error in self.results['errors'][:5]:
                print(f"     {error}")
                
        print(f"\n  💾 Report saved to: phase8_cleanup_report.json")
        
        return report
        
    def run(self):
        """Execute Phase 8 configuration cleanup"""
        print("\n" + "="*80)
        print("🚀 PHASE 8: CONFIGURATION CLEANUP")
        print("="*80)
        print(f"Mode: {'DRY RUN' if self.dry_run else 'LIVE EXECUTION'}")
        
        try:
            # Clean configuration files
            self.clean_settings_files()
            self.consolidate_env_files()
            self.update_gitignore()
            
            # Verify relationships
            self.verify_relationships()
            
            # Generate monitoring
            self.generate_monitoring_script()
            
            # Generate report
            report = self.generate_report()
            
            print("\n" + "="*80)
            if self.dry_run:
                print("✅ DRY RUN COMPLETE - Review results above")
                print("To execute cleanup, run with --execute")
            else:
                print("✅ PHASE 8 CLEANUP COMPLETE")
                print("\n📌 NEXT STEPS:")
                print("  1. Update .env file with production values")
                print("  2. Test with DEBUG=False locally")
                print("  3. Use settings_production.py for deployment")
                print("  4. Set environment variables in production")
                
            print("="*80)
            
            return report
            
        except Exception as e:
            import traceback
            self.log_console("ERROR", f"Cleanup failed: {e}", "error")
            self.results['errors'].append(str(e))
            traceback.print_exc()
            return None

def main():
    """Main execution"""
    import argparse
    
    parser = argparse.ArgumentParser(description='Phase 8 Configuration Cleanup')
    parser.add_argument('--execute', action='store_true',
                       help='Execute cleanup (default is dry run)')
    args = parser.parse_args()
    
    # Run cleanup
    cleaner = Phase8ConfigCleaner(dry_run=not args.execute)
    report = cleaner.run()
    
    if report:
        return 0
    return 1

if __name__ == "__main__":
    sys.exit(main())