#!/usr/bin/env python
"""
Test the actual Kakao links being generated by the Django views
"""
import os
import sys
import django
from django.test import Client

# Setup Django
sys.path.append('/Users/ian/Desktop/VIBECODE/PrimePath/primepath_project')
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'primepath_project.settings_sqlite')
django.setup()

def test_actual_generated_links():
    """Test what links are actually being generated by Django views"""
    print("=" * 60)
    print("🔍 TESTING ACTUAL DJANGO-GENERATED KAKAO LINKS")
    print("=" * 60)
    
    client = Client()
    
    print("🎓 Student Kakao Login:")
    try:
        response = client.get('/student/kakao/login/', follow=False)
        if response.status_code == 302:
            location = response.get('Location')
            print(f"   Status: {response.status_code}")
            print(f"   Redirect: {location}")
            
            # Check if phone_number is in the URL
            if 'phone_number' in location:
                print("   ❌ ISSUE FOUND: phone_number is in the scope!")
            else:
                print("   ✅ GOOD: No phone_number in scope")
                
        else:
            print(f"   Unexpected status: {response.status_code}")
            print(f"   Content: {response.content.decode()[:200]}...")
            
    except Exception as e:
        print(f"   Error: {e}")
    
    print("\n👨‍🏫 Teacher Kakao Login:")
    try:
        response = client.get('/auth/kakao/login/', follow=False)
        if response.status_code == 302:
            location = response.get('Location')
            print(f"   Status: {response.status_code}")
            print(f"   Redirect: {location}")
            
            # Check if phone_number is in the URL
            if 'phone_number' in location:
                print("   ❌ ISSUE FOUND: phone_number is in the scope!")
            else:
                print("   ✅ GOOD: No phone_number in scope")
                
        else:
            print(f"   Unexpected status: {response.status_code}")
            print(f"   Content: {response.content.decode()[:200]}...")
            
    except Exception as e:
        print(f"   Error: {e}")

def test_direct_view_import():
    """Test by importing views directly"""
    print("\n" + "=" * 60)
    print("🔍 TESTING VIEWS DIRECTLY")
    print("=" * 60)
    
    # Test student view
    try:
        from primepath_student.views.kakao_views import kakao_login
        from django.test import RequestFactory
        
        factory = RequestFactory()
        request = factory.get('/student/kakao/login/')
        request.session = {}
        
        response = kakao_login(request)
        location = response.get('Location')
        
        print("🎓 Student view direct call:")
        print(f"   Redirect URL: {location}")
        
        if 'phone_number' in location:
            print("   ❌ phone_number found in direct view call!")
        else:
            print("   ✅ No phone_number in direct view call")
            
    except Exception as e:
        print(f"   Student view error: {e}")
    
    # Test teacher view  
    try:
        from core.kakao_views import kakao_login as teacher_kakao_login
        
        request = factory.get('/auth/kakao/login/')
        request.session = {}
        
        response = teacher_kakao_login(request)
        location = response.get('Location')
        
        print("\n👨‍🏫 Teacher view direct call:")
        print(f"   Redirect URL: {location}")
        
        if 'phone_number' in location:
            print("   ❌ phone_number found in direct teacher view call!")
        else:
            print("   ✅ No phone_number in direct teacher view call")
            
    except Exception as e:
        print(f"   Teacher view error: {e}")

def main():
    print("🚨 DJANGO KAKAO LINK GENERATOR TEST")
    print("Testing what Django is actually generating vs what browser shows")
    print()
    
    test_actual_generated_links()
    test_direct_view_import()
    
    print("\n" + "=" * 60)
    print("📋 CONCLUSION")
    print("=" * 60)
    print("If Django-generated links don't have phone_number but browser does,")
    print("then the issue might be:")
    print("1. Browser cache (clear cache and try incognito)")
    print("2. JavaScript adding scope dynamically")
    print("3. Middleware modifying the redirect")
    print("4. Old browser bookmarks/history")

if __name__ == "__main__":
    main()