# Generated by Django 4.2.16 on 2025-08-24 08:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', 'add_kakao_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Unique student identifier created by student', max_length=20, unique=True)),
                ('phone_number', models.CharField(help_text="Student's phone number for authentication", max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')])),
                ('kakao_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primepath_student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'db_table': 'student_profile',
            },
        ),
        migrations.CreateModel(
            name='StudentClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(choices=[('PRIMARY_1A', 'Primary Grade 1A'), ('PRIMARY_1B', 'Primary Grade 1B'), ('PRIMARY_1C', 'Primary Grade 1C'), ('PRIMARY_1D', 'Primary Grade 1D'), ('PRIMARY_2A', 'Primary Grade 2A'), ('PRIMARY_2B', 'Primary Grade 2B'), ('PRIMARY_2C', 'Primary Grade 2C'), ('PRIMARY_2D', 'Primary Grade 2D'), ('PRIMARY_3A', 'Primary Grade 3A'), ('PRIMARY_3B', 'Primary Grade 3B'), ('PRIMARY_3C', 'Primary Grade 3C'), ('PRIMARY_3D', 'Primary Grade 3D'), ('PRIMARY_4A', 'Primary Grade 4A'), ('PRIMARY_4B', 'Primary Grade 4B'), ('PRIMARY_4C', 'Primary Grade 4C'), ('PRIMARY_4D', 'Primary Grade 4D'), ('PRIMARY_5A', 'Primary Grade 5A'), ('PRIMARY_5B', 'Primary Grade 5B'), ('PRIMARY_5C', 'Primary Grade 5C'), ('PRIMARY_5D', 'Primary Grade 5D'), ('PRIMARY_6A', 'Primary Grade 6A'), ('PRIMARY_6B', 'Primary Grade 6B'), ('PRIMARY_6C', 'Primary Grade 6C'), ('PRIMARY_6D', 'Primary Grade 6D'), ('MIDDLE_7A', 'Middle School Grade 7A'), ('MIDDLE_7B', 'Middle School Grade 7B'), ('MIDDLE_7C', 'Middle School Grade 7C'), ('MIDDLE_7D', 'Middle School Grade 7D'), ('MIDDLE_7E', 'Middle School Grade 7E'), ('MIDDLE_7F', 'Middle School Grade 7F'), ('MIDDLE_8A', 'Middle School Grade 8A'), ('MIDDLE_8B', 'Middle School Grade 8B'), ('MIDDLE_8C', 'Middle School Grade 8C'), ('MIDDLE_8D', 'Middle School Grade 8D'), ('MIDDLE_8E', 'Middle School Grade 8E'), ('MIDDLE_8F', 'Middle School Grade 8F'), ('MIDDLE_9A', 'Middle School Grade 9A'), ('MIDDLE_9B', 'Middle School Grade 9B'), ('MIDDLE_9C', 'Middle School Grade 9C'), ('MIDDLE_9D', 'Middle School Grade 9D'), ('MIDDLE_9E', 'Middle School Grade 9E'), ('MIDDLE_9F', 'Middle School Grade 9F'), ('HIGH_10A', 'High School Grade 10A'), ('HIGH_10B', 'High School Grade 10B'), ('HIGH_10C', 'High School Grade 10C'), ('HIGH_10D', 'High School Grade 10D'), ('HIGH_10E', 'High School Grade 10E'), ('HIGH_10F', 'High School Grade 10F'), ('HIGH_11A', 'High School Grade 11A'), ('HIGH_11B', 'High School Grade 11B'), ('HIGH_11C', 'High School Grade 11C'), ('HIGH_11D', 'High School Grade 11D'), ('HIGH_11E', 'High School Grade 11E'), ('HIGH_11F', 'High School Grade 11F'), ('HIGH_12A', 'High School Grade 12A'), ('HIGH_12B', 'High School Grade 12B'), ('HIGH_12C', 'High School Grade 12C'), ('HIGH_12D', 'High School Grade 12D'), ('HIGH_12E', 'High School Grade 12E'), ('HIGH_12F', 'High School Grade 12F')], help_text='Class code the student is assigned to', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_assignments_made', to='core.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='primepath_student.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Class Assignment',
                'verbose_name_plural': 'Student Class Assignments',
                'db_table': 'student_class_assignment',
                'indexes': [models.Index(fields=['student', 'is_active'], name='student_cla_student_781e6c_idx'), models.Index(fields=['class_code', 'is_active'], name='student_cla_class_c_7998ad_idx')],
                'unique_together': {('student', 'class_code')},
            },
        ),
    ]
