# Generated by Django 4.2.16 on 2025-08-24 08:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('primepath_routinetest', '0024_alter_classaccessrequest_class_code_and_more'),
        ('primepath_student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(help_text='Exam duration in minutes')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired'), ('abandoned', 'Abandoned')], default='not_started', max_length=20)),
                ('current_question', models.IntegerField(default=1)),
                ('answers', models.JSONField(default=dict, help_text="Student's answers stored as JSON")),
                ('auto_saved_at', models.DateTimeField(blank=True, help_text='Last auto-save timestamp', null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Final score as percentage', max_digits=5, null=True)),
                ('correct_answers', models.IntegerField(blank=True, null=True)),
                ('total_questions', models.IntegerField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('class_assignment', models.ForeignKey(help_text='The class context in which this exam was taken', null=True, on_delete=django.db.models.deletion.SET_NULL, to='primepath_student.studentclassassignment')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to='primepath_routinetest.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='primepath_student.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Exam Session',
                'verbose_name_plural': 'Student Exam Sessions',
                'db_table': 'student_exam_session',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='student_exa_student_8dbdad_idx'), models.Index(fields=['exam', 'status'], name='student_exa_exam_id_b85461_idx'), models.Index(fields=['class_assignment', 'created_at'], name='student_exa_class_a_a3cac9_idx')],
            },
        ),
    ]
