# Generated by Django 4.2.16 on 2025-08-24 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primepath_routinetest', '0026_routineexam_duration_routineexam_instructions'),
        ('primepath_student', '0002_studentexamsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexamsession',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_sessions', to='primepath_routinetest.routineexam'),
        ),
    ]
