# Generated by Django 4.2.16 on 2025-08-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepath_student', '0003_alter_studentexamsession_exam'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentexamsession',
            name='student_exa_student_8dbdad_idx',
        ),
        migrations.AddIndex(
            model_name='studentexamsession',
            index=models.Index(fields=['student', 'status', 'created_at'], name='student_exa_student_4e0fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamsession',
            index=models.Index(fields=['status', 'expires_at'], name='student_exa_status_47f8c7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamsession',
            index=models.Index(fields=['student', 'exam'], name='student_exa_student_b640a4_idx'),
        ),
    ]
