# Generated by Django 4.2.16 on 2025-08-24 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepath_student', '0004_remove_studentexamsession_student_exa_student_8dbdad_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(blank=True, help_text="Student's home address"),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Emergency contact phone number', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='grade',
            field=models.CharField(blank=True, choices=[('K', 'Kindergarten'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12'), ('UNI', 'University'), ('ADULT', 'Adult Student')], max_length=5),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent1_email',
            field=models.EmailField(blank=True, help_text='First parent/guardian email', max_length=254),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent1_name',
            field=models.CharField(blank=True, help_text='First parent/guardian name', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent1_phone',
            field=models.CharField(blank=True, help_text='First parent/guardian phone', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent2_email',
            field=models.EmailField(blank=True, help_text='Second parent/guardian email', max_length=254),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent2_name',
            field=models.CharField(blank=True, help_text='Second parent/guardian name', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent2_phone',
            field=models.CharField(blank=True, help_text='Second parent/guardian phone', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='recovery_email',
            field=models.EmailField(blank=True, help_text="Alternative email for password recovery (can be parent's email)", max_length=254),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school_address',
            field=models.TextField(blank=True, help_text='School address'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school_name',
            field=models.CharField(blank=True, help_text='Name of school student attends', max_length=200),
        ),
    ]
