# Generated by Django 4.2.16 on 2025-08-25 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepath_student', '0005_studentprofile_address_studentprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Student's phone number for authentication (optional for Kakao login)", max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
