# Generated by Django 4.2.16 on 2025-08-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primepath_student', '0006_make_phone_optional_for_kakao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='kakao_id',
        ),
    ]
