# Generated by Django 5.0.1 on 2025-07-31 13:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(help_text='Maximum file size: 10MB', upload_to='exams/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('timer_minutes', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_questions', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('passing_score', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher')),
                ('curriculum_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.curriculumlevel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='exams/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'm4a'])])),
                ('start_question', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('end_question', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='placement_test.exam')),
            ],
            options={
                'ordering': ['order', 'start_question'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('CHECKBOX', 'Select All'), ('SHORT', 'Short Answer'), ('LONG', 'Long Answer')], max_length=10)),
                ('correct_answer', models.TextField(help_text='For MCQ: single letter, For CHECKBOX: comma-separated letters')),
                ('points', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='placement_test.exam')),
            ],
            options={
                'ordering': ['question_number'],
                'unique_together': {('exam', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('school_name_manual', models.CharField(blank=True, max_length=200)),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('academic_rank', models.CharField(choices=[('TOP_10', 'Top 10%'), ('TOP_20', 'Top 20%'), ('TOP_30', 'Top 30%'), ('TOP_40', 'Top 40%'), ('TOP_50', 'Top 50%'), ('BELOW_50', 'Below 50%')], max_length=20)),
                ('difficulty_adjustments', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('percentage_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='placement_test.exam')),
                ('final_curriculum_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_sessions', to='core.curriculumlevel')),
                ('original_curriculum_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_sessions', to='core.curriculumlevel')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DifficultyAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment', models.IntegerField()),
                ('adjusted_at', models.DateTimeField(auto_now_add=True)),
                ('from_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments_from', to='core.curriculumlevel')),
                ('to_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments_to', to='core.curriculumlevel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='placement_test.studentsession')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_test.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='placement_test.studentsession')),
            ],
            options={
                'ordering': ['question__question_number'],
                'unique_together': {('session', 'question')},
            },
        ),
    ]
