# Generated by Django 5.0.1 on 2025-07-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='parent_phone',
            field=models.CharField(default='', help_text='Contact number for admission interview', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='academic_rank',
            field=models.CharField(choices=[('TOP_10', 'Top 10% (English class rank)'), ('TOP_20', 'Top 20% (English class rank)'), ('TOP_30', 'Top 30% (English class rank)'), ('TOP_40', 'Top 40% (English class rank)'), ('TOP_50', 'Top 50% (English class rank)'), ('BELOW_50', 'Below 50% (English class rank)')], max_length=20),
        ),
    ]
