# Generated by Django 5.0.1 on 2025-08-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_test', '0005_exam_default_options_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='name',
            field=models.CharField(default='Audio File', help_text='Descriptive name for this audio file', max_length=200),
        ),
    ]
