# Generated by Django 5.0.1 on 2025-07-31 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CORE', 'PRIME CORE'), ('ASCENT', 'PRIME ASCENT'), ('EDGE', 'PRIME EDGE'), ('PINNACLE', 'PRIME PINNACLE')], max_length=50, unique=True)),
                ('grade_range_start', models.IntegerField()),
                ('grade_range_end', models.IntegerField()),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_head_teacher', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprograms', to='core.program')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('program', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CurriculumLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='core.subprogram')),
            ],
            options={
                'ordering': ['subprogram__program__order', 'subprogram__order', 'level_number'],
                'unique_together': {('subprogram', 'level_number')},
            },
        ),
        migrations.CreateModel(
            name='PlacementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('min_rank_percentile', models.IntegerField(help_text='Minimum percentile (0-100)')),
                ('max_rank_percentile', models.IntegerField(help_text='Maximum percentile (0-100)')),
                ('priority', models.IntegerField(default=1, help_text='Lower number = higher priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curriculumlevel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher')),
            ],
            options={
                'ordering': ['priority', 'grade', 'min_rank_percentile'],
            },
        ),
    ]
