# Generated by Django 4.2.16 on 2025-08-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_teacher_authentication_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumlevel',
            name='internal_difficulty',
            field=models.IntegerField(blank=True, help_text='Internal difficulty tier (1=easiest, higher=harder). Multiple levels can share the same difficulty.', null=True),
        ),
        migrations.AlterField(
            model_name='examlevelmapping',
            name='slot',
            field=models.IntegerField(default=1, help_text='Slot position (1-5)'),
        ),
    ]
