# Generated by Django 4.2.16 on 2025-08-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_curriculumlevel_internal_difficulty_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='examlevelmapping',
            constraint=models.UniqueConstraint(fields=('exam',), name='unique_exam_per_mapping'),
        ),
    ]
