# Generated by Django 4.2.16 on 2025-08-18 09:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_student'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='student',
            new_name='core_studen_current_3aa275_idx',
            old_name='core_studen_current_3e8b47_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='core_studen_is_acti_d09166_idx',
            old_name='core_studen_is_acti_7c8b6c_idx',
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
