# Generated by Django 4.2.16 on 2025-08-18 14:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_rename_core_studen_current_3e8b47_idx_core_studen_current_3aa275_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent'), ('ADMIN', 'Administrator')], default='STUDENT', max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('alternate_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='South Korea', max_length=100)),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('grade_level', models.CharField(blank=True, max_length=50)),
                ('student_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('board_curriculum', models.CharField(blank=True, choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('IB', 'International Baccalaureate'), ('STATE', 'State Board'), ('KOREAN', 'Korean National Curriculum'), ('OTHER', 'Other')], max_length=10)),
                ('preferred_language', models.CharField(choices=[('EN', 'English'), ('KO', 'Korean'), ('HI', 'Hindi'), ('ZH', 'Chinese'), ('JA', 'Japanese'), ('ES', 'Spanish'), ('OTHER', 'Other')], default='EN', max_length=10)),
                ('medium_of_instruction', models.CharField(choices=[('EN', 'English'), ('KO', 'Korean'), ('HI', 'Hindi'), ('ZH', 'Chinese'), ('JA', 'Japanese'), ('ES', 'Spanish'), ('OTHER', 'Other')], default='EN', max_length=10)),
                ('parent_name', models.CharField(blank=True, max_length=200)),
                ('parent_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('parent_occupation', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50)),
                ('auth_provider', models.CharField(choices=[('EMAIL', 'Email'), ('GOOGLE', 'Google'), ('KAKAO', 'Kakao')], default='EMAIL', max_length=10)),
                ('social_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('social_profile_url', models.URLField(blank=True)),
                ('profile_photo_url', models.URLField(blank=True)),
                ('profile_completion_percentage', models.IntegerField(default=0)),
                ('profile_completed_at', models.DateTimeField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('special_needs', models.TextField(blank=True, help_text='Any special accommodations required')),
                ('previous_school', models.CharField(blank=True, max_length=255)),
                ('preferred_study_time', models.CharField(blank=True, choices=[('MORNING', 'Morning (6AM-12PM)'), ('AFTERNOON', 'Afternoon (12PM-6PM)'), ('EVENING', 'Evening (6PM-10PM)'), ('NIGHT', 'Night (10PM-12AM)')], max_length=10)),
                ('timezone', models.CharField(default='Asia/Seoul', max_length=50)),
                ('referral_source', models.CharField(blank=True, max_length=100)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_device', models.CharField(blank=True, max_length=255)),
                ('siblings_in_system', models.ManyToManyField(blank=True, to='core.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
                'indexes': [models.Index(fields=['account_type', 'is_active'], name='user_profil_account_5d1e79_idx'), models.Index(fields=['school_name', 'grade_level'], name='user_profil_school__2961c5_idx'), models.Index(fields=['auth_provider', 'social_id'], name='user_profil_auth_pr_235109_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('EMAIL', 'Email'), ('GOOGLE', 'Google'), ('KAKAO', 'Kakao')], max_length=10)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_auth_tokens',
                'unique_together': {('user', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'phone_verifications',
                'indexes': [models.Index(fields=['user', 'is_verified'], name='phone_verif_user_id_6302ff_idx'), models.Index(fields=['phone_number', 'otp_code'], name='phone_verif_phone_n_c0e2d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_method', models.CharField(choices=[('EMAIL', 'Email'), ('GOOGLE', 'Google'), ('KAKAO', 'Kakao')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_successful', models.BooleanField(default=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='login_histo_user_id_9416b0_idx'), models.Index(fields=['ip_address'], name='login_histo_ip_addr_3ce48d_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_verifications',
                'indexes': [models.Index(fields=['token'], name='email_verif_token_403404_idx'), models.Index(fields=['user', 'is_verified'], name='email_verif_user_id_87ed91_idx')],
            },
        ),
    ]
