# Generated by Django 4.2.16 on 2025-08-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_socialauthtoken_phoneverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='global_access_level',
            field=models.CharField(choices=[('FULL', 'Full Access'), ('VIEW_ONLY', 'View Only')], default='FULL', help_text='Global access level that applies to ALL assigned classes. FULL = can manage everything, VIEW_ONLY = can only view data.', max_length=20),
        ),
    ]
